### PR TITLE
Submit the search form if no result is selected

### PR DESCRIPTION
**Pull request by howdu**

### CODE REVIEW

**Comment by joshhanley** [comment]
@howdu thanks for this!

Makes sense to remove the `.prevent` and call that manually. Is there a way that logic can be inside the `enter()` method? I feel that would keep the markup cleaner. Then `this.selected` would also be accessible, so wouldn't need the getter.

Any chance you could add a test for this? If not, I will try and have a look at both of these later in the week.

**Comment by howdu** [comment]
@joshhanley no worries - I've updated so that the event is passed to `enter` function. 

Sorry I'm not sure how to write the test for it.

**Comment by joshhanley** [comment]
@howdu thanks, looks good! No worries, I will add a test for it.

**Comment by joshhanley** [comment]
@howdu thanks! Have tagged a release v0.1.9 with your changes 🙂

**Pull request merged**
